# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='type',
        ),
        migrations.AddField(
            model_name='article',
            name='describe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.ArticleType'),
        ),
        migrations.AddField(
            model_name='articletype',
            name='t_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='kw',
            field=models.ManyToManyField(null=True, to='backweb.KeyWord'),
        ),
    ]
