# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_auto_20181203_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kw',
            field=models.ManyToManyField(to='backweb.KeyWord'),
        ),
    ]
