# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_auto_20181203_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyWord',
            new_name='KeyWd',
        ),
    ]
