# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_auto_20181203_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='a_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='describe',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='f_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.ArticleType'),
        ),
    ]
