# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0006_article_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(null=True, upload_to='backweb'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backweb.ArticleType'),
        ),
    ]
