# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0007_auto_20181208_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='kw',
        ),
        migrations.AddField(
            model_name='article',
            name='taps',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
