# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0008_auto_20181208_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyWd',
        ),
    ]
