# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0009_delete_keywd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='taps',
            new_name='tags',
        ),
    ]
